### ISSUE TITLE
Always compiles nokogiri

### ISSUE THREAD

**Issue by kingdonb** [camertron/prebundler#7]
This is really neat, and it has sped up the parts of my pipeline something fierce, that run when something changed in Gemfile or Gemfile.lock! I localized everything including the S3 for prebundler (minio with a hostpath volume)

And harbor registry for local image

So `bundle install` with prebundler hits the cache every time, since builder is a local runner connected to GitHub Actions and there's never any fetch penalty

Image pushes could be made a bit faster by optimizing for performance I'm sure, but everything is local and going across a fast 1-gigabit link!

And deploys are super fast because the staging host is also here on the local network, so it can pull images from the local harbor super fast, just as well as builder can push them. In fact it probably doesn't even have to pull, since the same host has pushed the image. So this is really fast. It has got down to 2 minutes from end to end and with webhooks, the image build and deployment goes very smoothly and fast.

When I tell you that it's actually compiling Nokogiri for some reason in the middle of all this (when Nokogiri definitely hasn't changed, and it doesn't seem to need to compile any other native extensions at all...) wouldn't it be so much faster still, if it didn't do that either?

https://github.com/kingdonb/kuby_test/runs/4671817512?check_suite_focus=true

<img width="659" alt="Screen Shot 2021-12-30 at 11 36 16 PM" src="https://user-images.githubusercontent.com/3286998/147803582-d48a00fe-cd3e-4864-bb8e-af1a16a2cfa2.png">

<img width="961" alt="Screen Shot 2021-12-30 at 11 36 37 PM" src="https://user-images.githubusercontent.com/3286998/147803586-87c0e9d2-8347-42d1-b4bb-aa38d217036d.png">

Ever seen it do that? Got a workaround mayhap? (Happy new year, and good health to you and all your family!)

This is with prebundler so it's actually very fast, but this screenshot suggests I can shave off as much as another 50s if I can get it to not do that! Such gains! Much fantasticness 😄 it's already so much faster than it was before.

**Comment by kingdonb** [comment]
I think I figured it out,

If I haven't actually run `bundle install` on the target platform then I'll be missing the requisite lines in Gemfile.lock whose absence cause this issue. (commit that follows resolves this issue in my repo, I think 🤞 )

**Comment by kingdonb** [comment]
100% that was my problem. No issue in prebundler. Remember to run `bundle install` on your target platform and commit the resulting changes to Gemfile.lock in order to avoid this issue 👍

**Comment by camertron** [comment]
Nice, thanks for posting that follow-up @kingdonb  :) I actually just published a new version yesterday that always runs `bundle lock` before installing anything. Hopefully that helps too :)

**Comment by kingdonb** [comment]
Nice, I'll rebase and check it out! Looks like you ran into a lot of the same issues I have.

I've got Rails 7 and Ruby 3.0.3 running on my own Kuby-core and kube-dsl fork now, with my own prebundler fork, https://github.com/kingdonb/scrob-web and it runs tests now as well! So I got that going for me, which is nice.
